### ISSUE TITLE
Failed to Load Encoder

### ISSUE THREAD

**Issue by nfprojets** [nianticlabs/ace#12]
Hi, I tried to reproduce with the 7Scene chess scene but I got this error 

`INFO:ace_trainer:Loaded training scan from: datasets/7scenes_chess -- 4000 images, mean: 0.45 -0.74 0.30
Traceback (most recent call last):
  File "train_ace.py", line 126, in <module>
    trainer = TrainerACE(options)
  File "/home/nanda/dev/ace/ace_trainer.py", line 92, in __init__
    encoder_state_dict = torch.load(self.options.encoder_path, map_location="cpu")
  File "/home/nanda/.conda/envs/ace/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/nanda/.conda/envs/ace/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

Seems like I can't load the pre-trained encoder that you already shared. Do you have any idea about this? Thanks!

**Comment by nfprojets** [comment]
Gonna close this because solved by downloading the encoder with raw data~

**Comment by tcavallari** [comment]
Hello!

For future reference, this was because we store the encoder as a Git LFS file in the repository, and it probably wasn't configured correctly in your system. You can have a look at the official guide, [here](https://github.com/git-lfs/git-lfs#getting-started), to configure it.
