### ISSUE TITLE
Cannot download encoder weights

### ISSUE THREAD

**Issue by sontung** [nianticlabs/ace#13]
Hi,

I tried to pull the code and got this error. Is it possible to upload the encoder weight somewhere else? THanks.

Downloading ace_encoder_pretrained.pt (22 MB)
Error downloading object: ace_encoder_pretrained.pt (c69ca93): Smudge error: Error downloading ace_encoder_pretrained.pt (c69ca934d82056c9f2e9be9582d85841bd53355ac04a007c11618b1760c00a8c): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by tcavallari** [comment]
Hi, thanks for reporting this.

I replaced the LFS weights with a regular git file, can you try cloning again?
