### ISSUE TITLE
Support principle point intrinsic parameters in training

### ISSUE THREAD

**Issue by hazel-sudz** [nianticlabs/ace#15]
>         # Create the intrinsics matrix.
>         intrinsics = torch.eye(3)
>         intrinsics[0, 0] = focal_length
>         intrinsics[1, 1] = focal_length
>         # Hardcode the principal point to the centre of the image.
>         intrinsics[0, 2] = image.shape[2] / 2
>         intrinsics[1, 2] = image.shape[1] / 2
https://github.com/nianticlabs/ace/blob/2507cdb01146898b011e3e91e716d7399a533c5c/dataset.py#L489

Assuming I'm understanding this correctly, would be happy to make a PR for this. We are looking to train from Arkit IOS data where the optical center can vary from frame-to-frame as a result of some distortion correction that apple seems to be doing.

**Comment by tcavallari** [comment]
Hi, thanks for bringing it up. We'd be happy to accept a PR that introduced support for reading the full intrinsics (fx,fy, cx, cy) from the calibration files.

I think [this line](https://github.com/nianticlabs/ace/blob/2507cdb01146898b011e3e91e716d7399a533c5c/dataset.py#L365) would need to be changed to read either a single value (to continue supporting the paper datasets that only provide a single focal length), or 4 values.

After that, the changes to the rest of the code should be reasonably straightforward.

**Comment by tcavallari** [comment]
Thanks for the contribution.

**Comment by Mingyuan1997** [comment]
Thanks for the contribution. Could you share some suggetions how we can get a posed RGB video frame from IOS and merge with this repo?

Best
