### ISSUE TITLE
Need some clarification on what pose file mean

### ISSUE THREAD

**Issue by willdzeng** [nianticlabs/ace#23]
Hi,
I am trying to generate some training data directly to test ACE out, one question is about the pose file,
are poses under train/poses camera_to_world transform or world_to_camera transform? 
given the definition of A_to_B transform means transforming a point from coordinate A to coordinate B
e.g.
```
point_B = A_to_B_transform * point_A
```
Thanks!

**Comment by FFFOCUS** [comment]
camera_to_world transform

**Comment by tcavallari** [comment]
Correct!

The dataset class returns the following objects:

`image, image_mask, pose, pose_inv, intrinsics, intrinsics_inv, coords, str(self.rgb_files[idx])`.

In this context `pose` is `camera_to_world` (read directly from the pose file in the dataset folders), and `pose_inv` is its inverse, `world_to_camera`.

**Comment by willdzeng** [comment]
Thanks for the quick response, a follow up question: what is the definition of camera coordinate, is it classical
X-right
Y-down
Z- forward
![image](https://github.com/nianticlabs/ace/assets/12994633/ede78a69-b0da-47bd-b34d-5e5f852fe012)
https://learnopencv.com/geometry-of-image-formation/

**Comment by ebrach** [comment]
Yes, ACE uses the OpenCV convention.
