### ISSUE TITLE
3D models for the wayspot dataset

### ISSUE THREAD

**Issue by sontung** [nianticlabs/ace#25]
Hi,
Is it possible that you can share the SfM models for each of the scenes in the wayspot dataset? Many thanks.

**Comment by ebrach** [comment]
Hi,

the Wayspots dataset was sourced from the larger [map-free dataset](https://research.nianticlabs.com/mapfree-reloc-benchmark/dataset), where the SfM models for all scenes in the training set are available for download. This includes the SfM models of all Wayspots scenes.

However, we choose to not make these SfM models available directly as part of the Wayspots release to discourage people from using the SfM models to relocalise against. These SfM models have been built by bundle-adjusting test and training images jointly. If you relocalise against the SfM models (by matching query images to the SfM point cloud), you results might be severely biased, and overly optimistic.

The preferable way of applying feature matching methods on the Wayspots dataset is to re-built your own SfM model using only Wayspots mapping sequence where mapping poses come from ARKit/ARCore. Even so, feature matching results might still be biased as we have discussed in the [ACE paper](https://arxiv.org/pdf/2305.14059.pdf), section B.2.2. For more information about the difficulty of comparing different families of relocalizers (such as scene coordinate regression and feature matching), consider [this paper](https://arxiv.org/abs/2109.00524).

Best,
Eric

**Comment by sontung** [comment]
Hi,

Thanks for the answer. I am experimenting with a better way to train ACE with heuristic from the SFM models. So if you can give me the scene ID to the 3D models, I can extend the evaluation to Wayspots as well and that would be lovely.
