### ISSUE TITLE
Pretrain Feature Extractor Backbone Network from ScanNet

### ISSUE THREAD

**Issue by the-masses** [nianticlabs/ace#29]
Thank you very much for the code on Git Hub. In paper 3.3 Backbone Training, you said "Instead of training the backbone with one regression head for a single scene, we train it with N regression heads for N scenes, in parallel." I'd like to know exactly how many scenarios this N represents using for parallel training. In addition to that, would you mind sharing how to select 100 scenarios in ScanNet? Very much looking forward to your reply.

**Comment by ebrach** [comment]
Hi. I think the answers you are looking for are available in the Supplement, section A.1. Feel free to re-open this issue if you have more questions.

**Comment by the-masses** [comment]
I found the answer. Thank you very much for your reply.
