### ISSUE TITLE
support fx and fy

### ISSUE THREAD

**Issue by Khoa-NT** [nianticlabs/ace#3]
Hi, 
Thank you for the amazing paper and for sharing the code.
From [this](https://github.com/nianticlabs/ace/blob/main/datasets/dataset_util.py#L61), I saw the code is using single focal length `f`.
Currently, my colmap result returned fx & fy. 
I would like to ask if is it ok to run with only fx from your code.
Or can you support the fx and fy?

**Comment by tcavallari** [comment]
Hello, thanks for your feedback.

You are correct that the code at the moment uses a single focal length for both `x` and `y`. There are two options:
- If your COLMAP focal lengths are similar enough, you could average them and use the code as it is.
- Alternatively, you could store them both in the various calibration files (separated by space), then update this line: https://github.com/nianticlabs/ace/blob/main/dataset.py#L365 to read them both as a tensor of two elements. You also need to update these two lines: https://github.com/nianticlabs/ace/blob/main/dataset.py#L487 to use them both in the camera calibration matrix. The rest of the training/testing code should work out of the box.

**Comment by Khoa-NT** [comment]
Hello @tcavallari,
Thank you for your prompt reply and detailed solutions.
I'm currently making a script to convert COLMAP binary to your `pgt` format to train the model with my customs dataset.
I will try both of the solutions and update you later.
