### ISSUE TITLE
Question with regards to results on Indoor6 dataset

### ISSUE THREAD

**Issue by AustrianOakvn** [nianticlabs/ace#35]
Hi, thank you for great work.
I try to use ACE on the Indoor6 dataset provided by the following: https://github.com/microsoft/SceneLandmarkLocalization. However, the results are not so good, the translation error reach 1 meter and the rotation error can be up to 100 degrees. Because indoor6 dataset is collected at different time and day, it contains high illumination variations. Could ACE work in such cases, are there any configuration that i missed?
![01-frame000072](https://github.com/nianticlabs/ace/assets/46952800/e137c7a9-a8e2-4d7b-96de-0dfda46fb32b)
![04-frame000022](https://github.com/nianticlabs/ace/assets/46952800/7c42f9dc-60e2-4226-b45b-4afa1a812dae)
![15-frame000143](https://github.com/nianticlabs/ace/assets/46952800/2352bf79-3ab7-46e1-984a-4df56e395b8b)

**Comment by ebrach** [comment]
Hi, 

we did not try the Indoor-6 dataset but the images you share look challenging for ACE. The Indoor-6 paper contains numbers for DSAC*. They ran DSAC* in "poses+3d-model" mapping mode which is a slightly easier task than ACE's "poses-only" mapping mode. That said, I think one can expect similar performance of ACE and DSAC* if ACE mapping succeeds. Whether or not ACE mapping succeeds can be somewhat checked via the visualisation capabilities of ACE. 

I would recommend to check the visualisations and see whether the mapping camera poses look OK (to rule out any dataset conversion issue), and whether ACE learns plausible scene geometry.

Best,
Eric

**Comment by AustrianOakvn** [comment]
Thank you for your response, after checking the code and testing ACE with all scene in the indoor6, the performance was just like you said, it is quite close to DSAC*.
translation error (cm)/rotation error (deg)
|       | scene1    | scene2a | scene3    | scene4a  | scene5    | scene6  |
|-------|-----------|---------|-----------|----------|-----------|---------|
| DSAC* | 12.3/2.06 | 7.9/0.9 | 13.1/2.34 | 3.7/0.95 | 40.7/6.72 | 6.0/1.4 |
| ACE   | 13.6/2.1  | 6.8/0.7 | 8.1/1.3   | 4.8/0.9  | 14.7/2.3  | 6.1/1/1 |

Again, ACE is really impressive in term of speed and memory efficiency but I wonder for example what can be use to improve ACE on such cases mentioned above with high illumination and drastic environmental changes.

**Comment by ebrach** [comment]
I think the feature backbone of ACE needs to be improved to be more robust to such condition changes.

I will close this issue since, I think, your original question was answered.

**Comment by Easonyesheng** [comment]
Hi @AustrianOakvn 
I encountered the same question on reproducing ACE on Indoor6, that is the translation error reach 1 meter and the rotation error can be up to 100 degrees.
I wonder how to achieve the results you reported [here](https://github.com/nianticlabs/ace/issues/35#issuecomment-2194446835).
Is there any specific hyper-parameters to select in training?
Thanks for any suggestions.
