### ISSUE TITLE
AceZero Adaptation Issues with Ace

### ISSUE THREAD

**Issue by GottenZZP** [nianticlabs/ace#37]
Hello, I tried visualizing the training of the Ace method by adding the "--render_visualization" parameter, but found that using the pose parameters obtained from the 3D reconstruction in Colmap did not effectively model the point cloud in Ace (or did not model it at all). I am wondering if the large amount of reflection in my dataset environment is causing this issue (as my scene is an indoor environment with highly reflective materials on the floor and floor-to-ceiling windows). I noticed that your team seems to have released a new paper this year called AceZero, which appears to focus on SfM modeling and scene coordinate reconstruction. Could you please confirm if the poses_final.txt file produced after training with the new AceZero method can be well adapted to the current Ace method? Looking forward to your response.

**Comment by ebrach** [comment]
Answered here: https://github.com/nianticlabs/acezero/issues/25

Feel free to re-open if questions remain.

Best,
Eric
