### ISSUE TITLE
Config for Cambridge dataset

### ISSUE THREAD

**Issue by LexaNagiBator228** [nianticlabs/ace#39]
Hello, could you plz suggest the training and test config parameters  for Cambridge Landmarks dataset? The default config works quite good for 7 scenes, but test performance for Cambridge Landmarks is not that good. Did you use different training parameters?   
![frame_00109](https://github.com/user-attachments/assets/a0165133-9d61-4517-900e-2f0ca7ba783c)

**Comment by tcavallari** [comment]
Hello, apologies for the delay.

Yes, the default config is not great on the Cambridge Landmarks dataset, we ran some analysis in the paper and found that using a simple ensemble model (where the scene is split into multiple disjoint clusters and an ACE network is trained for each cluster) we could get much better performance.

You can try using [this script](https://github.com/nianticlabs/ace/blob/main/scripts/train_cambridge_ensemble.sh) to to train an ensemble of 4 ACE models: `./scripts/train_cambridge_ensemble.sh 4`. That should replicate our paper results.

You can also play with the training parameters, e.g. increasing the number of training iterations/buffer size/batch size, etc...

Let us know if you have further questions.

**Comment by ebrach** [comment]
Closing for now. Feel free to re-open if you have further questions.
