### ISSUE TITLE
Segmentation Fault in a Newer Environment

### ISSUE THREAD

**Issue by kevintsq** [nianticlabs/ace#40]
https://github.com/nianticlabs/ace/blob/e9e90f2d02ee92c348bf411a5a60e230af6c315e/dsacstar/dsacstar_util.h#L367

It may be this line that causes the problem.

**Comment by ebrach** [comment]
Hi. Please provide more context, i.e. the stack trace and which packages you updated. 

But in general: We provide an environment with which you should be able to run our code and reproduce our results. Beyond that, we cannot provide support if you choose to run the code with other library versions.

Best,
Eric
