### ISSUE TITLE
Some doubts about the operation of ACE,

### ISSUE THREAD

**Issue by neng-wang** [nianticlabs/ace#41]
Hello author, 
thank you for open-sourcing such excellent work. Regarding the operational mechanism of the paper, I have some questions:

1. The paper mentions a map size of 4MB, does this refer to the memory of the ACE network? Does that mean there is no explicit map used for relocalization, such as a point cloud map?

2. How does ACE operate during the inference process? When a frame of image is obtained, is it necessary to first estimate the 3D coordinates corresponding to each pixel? Or can it directly output the pose of this frame of image in an end-to-end fashion?

3. Is Scene Coordinate Regression only needed during training?

**Comment by ebrach** [comment]
Hi,

1. The 4MB refer to the memory of the network weights, e.g. when you store the network on disk. The network itself is the map, and there is no other explicit and no point cloud. You need nothing else than the 4MB network per scene (and the ACE encoder network, but it is scene agnostic)
2. The network predicts scene coordinates, and from those you estimate the pose with RANSAC and PnP. ACE does not predict the pose directly, and it is not trained end-to-end (in the sense of pose regression).
3. See point two: No, scene coordinate regression is the core of the entire framework, including test time.

Hope that helps, and feel free to re-open if you have more questions,
Eric

**Comment by Gatsby23** [comment]
> Hi,
> 
> 1. The 4MB refer to the memory of the network weights, e.g. when you store the network on disk. The network itself is the map, and there is no other explicit and no point cloud. You need nothing else than the 4MB network per scene (and the ACE encoder network, but it is scene agnostic)
> 2. The network predicts scene coordinates, and from those you estimate the pose with RANSAC and PnP. ACE does not predict the pose directly, and it is not trained end-to-end (in the sense of pose regression).
> 3. See point two: No, scene coordinate regression is the core of the entire framework, including test time.
> 
> Hope that helps, and feel free to re-open if you have more questions, Eric

Thank you for your response. Following up on this topic, I have a question regarding coordinate systems that I'd like to trouble you with:

I currently have a dataset that includes both image data and pose data, where the pose data is provided in the IMU coordinate system. As you mentioned, the training process is somewhat analogous to building a map. Based on that, it seems the resulting map should also be constructed in the IMU coordinate system—am I understanding that correctly? If so, when performing image relocalization, would the relocalized camera pose also be in the IMU coordinate system?

However, from what I’ve read, ACE estimates the pose of a query image by matching learned features to scene coordinates (which, if I understand correctly, are in the camera coordinate system?). From this perspective, it seems the estimated pose should be expressed in the camera coordinate system instead?

This question has been puzzling me for quite a while, and I’m really looking forward to your clarification.

**Comment by ebrach** [comment]
Hey!

ACE operates with cam-2-world poses. This is what we train with, and this is what RANSAC predicts. Scene coordinates are predicted in world space. Note however that the **output file** of ACE contains the inverse, world-2-cam poses (following COLMAP).

In your case the IMU coordinate system is the world coordinate system.  

ACE assumes that poses follow the OpenCV coordinate convention.

See also my answer here: https://github.com/nianticlabs/ace/issues/44#issuecomment-2834543439

Best,
Eric

**Comment by Gatsby23** [comment]
> Hey!
> 
> ACE operates with cam-2-world poses. This is what we train with, and this is what RANSAC predicts. Scene coordinates are predicted in world space. Note however that the **output file** of ACE contains the inverse, world-2-cam poses (following COLMAP).
> 
> In your case the IMU coordinate system is the world coordinate system.
> 
> ACE assumes that poses follow the OpenCV coordinate convention.
> 
> See also my answer here: [#44 (comment)](https://github.com/nianticlabs/ace/issues/44#issuecomment-2834543439)
> 
> Best, Eric

Thank you for your explanation. However, there’s still something I don’t quite understand—please allow me to explain it in more detail, and I truly appreciate your patience:

If I use the IMU poses as the training poses, would the resulting scene coordinates then be expressed in the IMU coordinate system of the first frame (i.e., the world coordinate system)? If so, wouldn’t that make the output not directly applicable for pose estimation? My concern is that DSAC outputs a world-to-camera transformation, which seems inconsistent with this setup.

**Comment by ebrach** [comment]
Not sure I understand your issue - probably there is something about the nature of "IMU poses" that I do not know about. I assume these are tracking poses relative to the first frame, where the first frame has the identity pose? 

If so, this is your world coordinate system. Scene coordinates are predicted in that world coordinate system and define image-to-world correspondences. From image-to-world correspondences, we estimate the query pose in world coordinate space.

**Comment by Gatsby23** [comment]
> Not sure I understand your issue - probably there is something about the nature of "IMU poses" that I do not know about. I assume these are tracking poses relative to the first frame, where the first frame has the identity pose?
> 
> If so, this is your world coordinate system. Scene coordinates are predicted in that world coordinate system and define image-to-world correspondences. From image-to-world correspondences, we estimate the query pose in world coordinate space.

Thank you for your patient explanation. I’ve figured it out now.
