### ISSUE TITLE
generate reconstructions

### ISSUE THREAD

**Issue by Fungungun** [nianticlabs/ace#6]
Hi 

Thanks for your work. Just wondering if it's possible to generate the point cloud of the scene with the trained weights as shown in the demo video?

Thanks

**Comment by ebrach** [comment]
Hi,

yes, that is possible. The visualisation code is fully integrated, and you can create these demo videos yourself. Just run the [ACE evaluation](https://github.com/nianticlabs/ace#ace-evaluation) script with a pre-trained model, and append `--render_visualization True`. 

If you want to export the point cloud, that is currently not implemented but possible as well. See how the test script extracts the point cloud from the network [here](https://github.com/nianticlabs/ace/blob/6515d1df5bb0c2c803137baa52a901fe2052089a/ace_visualizer.py#LL735C9-L735C9) by using [this function](https://github.com/nianticlabs/ace/blob/6515d1df5bb0c2c803137baa52a901fe2052089a/ace_vis_util.py#L398).

The easiest way for an export is to dump the returned `pc_xyz, pc_clr` tensors to a text file with XYZRGB per point on a new line. You can open these files with CloudCompare or similar tools.

**Comment by tcavallari** [comment]
Closing for now. Happy to continue the discussion if more questions come up.
