### ISSUE TITLE
fisheye camera case

### ISSUE THREAD

**Issue by dong-won-shin** [nianticlabs/ace#7]
Thank you for this great relocalization framework!
I found out that the demo results with the dataset you provided are awesome in my machine.

And I have a simple question while trying to apply this framework on my project.
Could it be applied to fisheye camera case if we have correct extrinsic camera poses?
I guess the reprojection error need to be changed to appropriate form considering the lens distortion..
Could I get some advices?

Thank you in advance.

**Comment by ebrach** [comment]
Hi, 

the current code does not support lens distortion. You would have to add it to the reprojection loss, but also to the inference code in `dsacstar`. 

It might be easier to undistort your fisheye images using external tools before passing them to our pipeline.

**Comment by dong-won-shin** [comment]
Thank you for your advice!
I guess the useful ROI area of undistorted image would be less.. but I would try that one. :-)
