### ISSUE TITLE
render_visualization error

### ISSUE THREAD

**Issue by keepgoing2996** [nianticlabs/ace#9]
Hi I am getting this error after setting --render_visualization=True, any idea about that?
INFO:OpenGL.platform.ctypesloader:Failed to load library ( 'libEGL.so.0' ): libEGL.so.0: cannot open shared object file: No such file or directory
WARNING:ace_visualizer:Rendering failed, trying again!

**Comment by tcavallari** [comment]
Hello.

Looks like an issue with missing libraries. Could you make sure the nvidia drivers are installed correctly? They should have installed all the required dependencies transitively. We ran our tests with driver version 520.

If that's already the case, maybe you can try running `sudo apt install libegl1 libegl-mesa0` to install the egl packages manually.

**Comment by ebrach** [comment]
Maybe this information of PyRender (which we use for the visualisation) is useful for you as well:
https://pyrender.readthedocs.io/en/latest/examples/offscreen.html

We set the rendering backend here in case you want to choose something else: https://github.com/nianticlabs/ace/blob/6515d1df5bb0c2c803137baa52a901fe2052089a/ace_visualizer.py#L4

**Comment by keepgoing2996** [comment]
> Hello.
> 
> Looks like an issue with missing libraries. Could you make sure the nvidia drivers are installed correctly? They should have installed all the required dependencies transitively. We ran our tests with driver version 520.
> 
> If that's already the case, maybe you can try running `sudo apt install libegl1 libegl-mesa0` to install the egl packages manually.
Seems like I already installed that, and here is my nvidia-driver information

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libegl-mesa0 is already the newest version  (21.2.6-0ubuntu0.1~20.04.2).
libegl-mesa0 set to manually installed.
libegl1 is already the newest version (1.3.2-1~ubuntu0.20.04.2).
libegl1 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 167 not upgraded.


 NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.6

**Comment by keepgoing2996** [comment]
> Maybe this information of PyRender (which we use for the visualisation) is useful for you as well: https://pyrender.readthedocs.io/en/latest/examples/offscreen.html
> 
> We set the rendering backend here in case you want to choose something else:
> 
> https://github.com/nianticlabs/ace/blob/6515d1df5bb0c2c803137baa52a901fe2052089a/ace_visualizer.py#L4

Right I tried to use osmesa, and got similar error as well. 

  File "code/ace/ace_visualizer.py", line 621, in _render_mapping_frame_from_buffers
    current_frame = self._render_frame_from_buffers_safe()
  File "code/ace/ace_visualizer.py", line 569, in _render_frame_from_buffers_safe
    raise RuntimeError("Re-rendering failed too often...")
RuntimeError: Re-rendering failed too often...

**Comment by ebrach** [comment]
I see two potential courses of action:

1) Independent of ACE (but in the same Conda environment) try to get a minimal example of PyRender to work:
https://pyrender.readthedocs.io/en/latest/examples/quickstart.html
To make sure that all libraries and drivers are setup correctly.

2) Remove the `try ... except` block in `_render_frame_from_buffers_safe` here: https://github.com/nianticlabs/ace/blob/6515d1df5bb0c2c803137baa52a901fe2052089a/ace_visualizer.py#L563-L567
This will forward the actual rendering exception to the console, which might provide more information than the generic runtime error we forward if rendering fails too often.

**Comment by tcavallari** [comment]
Closing for now. Happy to continue the discussion if follow-up questions come up.

**Comment by Isletfall** [comment]
Hi,Thank you for your great work.
I met the same question after setting --render_visualization=True,and got some informations:
Traceback (most recent call last):
  File "./train_ace.py", line 127, in <module>
    trainer.train()
  File "/home/code/ace/ace_trainer.py", line 184, in train
    self.run_epoch()
  File "/home/code/ace/ace_trainer.py", line 373, in run_epoch
    self.training_step(
  File "/home/code/ace/ace_trainer.py", line 470, in training_step
    self.ace_visualizer.render_mapping_frame(vis_scene_coords, vis_errors)
  File "/home/code/ace/ace_visualizer.py", line 654, in render_mapping_frame
    self._render_mapping_frame_from_buffers()
  File "/home/code/ace/ace_visualizer.py", line 621, in _render_mapping_frame_from_buffers
    current_frame = self._render_frame_from_buffers_safe()
  File "/home/code/ace/ace_visualizer.py", line 569, in _render_frame_from_buffers_safe
    raise RuntimeError("Re-rendering failed too often...")
RuntimeError: Re-rendering failed too often...

I tried to set the rendering backend to osmesa and remove the try ... except block in _render_frame_from_buffers_safe,but got the same error,I'd like to know how to solve these problem

Looking forward to your response.

**Comment by ebrach** [comment]
To debug, you first have to get to the actual error. You said that you removed our custom try ... except block but got the same error. Not sure I understand. If you remove our custom exceptions (as part of the try ... except block), they cannot be raised anymore?
